# Environment information

In [1]:
import sys
print("Python:", sys.version)

import numpy as np
print("NumPy:", np.__version__)

import pandas as pd
print("Pandas:", pd.__version__)

import sklearn
print("Scikit-learn:", sklearn.__version__)

import spacy
print("SpaCy:", spacy.__version__)

Python: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
NumPy: 1.19.5
Pandas: 1.1.5
Scikit-learn: 0.24.1
SpaCy: 2.3.5


# Pandas example

In [2]:
df_bites = pd.read_csv('datasets/Health_AnimalBites.csv', sep=',', quoting=0, header=0)

#print(type(df))

df_bites.head()

bite_date SpeciesIDDesc BreedIDDesc GenderIDDesc       color  \
0  1985-05-05 00:00:00           DOG         NaN       FEMALE  LIG. BROWN   
1  1986-02-12 00:00:00           DOG         NaN      UNKNOWN   BRO & BLA   
2  1987-05-07 00:00:00           DOG         NaN      UNKNOWN         NaN   
3  1988-10-02 00:00:00           DOG         NaN         MALE   BLA & BRO   
4  1989-08-29 00:00:00           DOG         NaN       FEMALE     BLK-WHT   

   vaccination_yrs     vaccination_date victim_zip AdvIssuedYNDesc  \
0              1.0  1985-06-20 00:00:00      40229              NO   
1              NaN                  NaN      40218              NO   
2              NaN                  NaN      40219              NO   
3              NaN                  NaN        NaN              NO   
4              NaN                  NaN        NaN              NO   

  WhereBittenIDDesc      quarantine_date DispositionIDDesc head_sent_date  \
0              BODY  1985-05-05 00:00:00           UNKNOWN            NaN   
1              BODY  1986-02-12 00:00:00           UNKNOWN            NaN   
2              BODY  1990-05-07 00:00:00           UNKNOWN            NaN   
3              BODY  1990-10-02 00:00:00           UNKNOWN            NaN   
4              BODY                  NaN           UNKNOWN            NaN   

  release_date ResultsIDDesc  
0          NaN       UNKNOWN  
1          NaN       UNKNOWN  
2          NaN       UNKNOWN  
3          NaN       UNKNOWN  
4          NaN       UNKNOWN

In [3]:
df_alexa = pd.read_csv('datasets/amazon_alexa.tsv', sep='\t', quoting=0, header=0)

df_alexa.head()

rating       date         variation  \
0       5  31-Jul-18  Charcoal Fabric    
1       5  31-Jul-18  Charcoal Fabric    
2       4  31-Jul-18    Walnut Finish    
3       5  31-Jul-18  Charcoal Fabric    
4       5  31-Jul-18  Charcoal Fabric    

                                    verified_reviews  feedback  
0                                      Love my Echo!         1  
1                                          Loved it!         1  
2  Sometimes while playing a game, you can answer...         1  
3  I have had a lot of fun with this thing. My 4 ...         1  
4                                              Music         1

In [4]:
df_alexa.describe()

rating     feedback
count  3150.000000  3150.000000
mean      4.463175     0.918413
std       1.068506     0.273778
min       1.000000     0.000000
25%       4.000000     1.000000
50%       5.000000     1.000000
75%       5.000000     1.000000
max       5.000000     1.000000

# Scikit-learn example

In [5]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df_alexa, test_size=0.2, shuffle=True, random_state=13) # fix the seed

In [6]:
df_train.describe()

rating    feedback
count  2520.000000  2520.00000
mean      4.453175     0.91746
std       1.079690     0.27524
min       1.000000     0.00000
25%       4.000000     1.00000
50%       5.000000     1.00000
75%       5.000000     1.00000
max       5.000000     1.00000

In [7]:
df_test.describe()

rating    feedback
count  630.000000  630.000000
mean     4.503175    0.922222
std      1.022399    0.268034
min      1.000000    0.000000
25%      4.000000    1.000000
50%      5.000000    1.000000
75%      5.000000    1.000000
max      5.000000    1.000000

## TF-IDF

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names())

print(X.shape)

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
(4, 9)


### Displaying sparse matrix

In [21]:
#print(X)

#print(type(X))

#print(X.toarray())
#print(X.A)

#print(type(X.toarray()))
#print(type(X.A))

X.data = np.round(X.data, 3)
print(X.toarray())

[[0.    0.47  0.58  0.384 0.    0.    0.384 0.    0.384]
 [0.    0.688 0.    0.281 0.    0.539 0.281 0.    0.281]
 [0.512 0.    0.    0.267 0.512 0.    0.267 0.512 0.267]
 [0.    0.47  0.58  0.384 0.    0.    0.384 0.    0.384]]


# SpaCy example

In [22]:
#nlp = spacy.load("en_core_web_sm", disable=["ner"])

#! python3 -m spacy download en
nlp = spacy.load("en")

print(type(nlp))
print("Pipeline:", nlp.pipe_names)

<class 'spacy.lang.en.English'>
Pipeline: ['tagger', 'parser', 'ner']


In [11]:
doc = nlp("spaCy is a free, open-source library for advanced Natural Language Processing (NLP) in Python.")

print(type(doc))

<class 'spacy.tokens.doc.Doc'>


In [12]:
from spacy import displacy

displacy.render(doc, style="dep", jupyter=True, options={'distance': 130})

In [13]:
displacy.render(doc, style="ent", jupyter=True)

## List of tokens

In [25]:
print([token for token in doc])

[spaCy, is, a, free, ,, open, -, source, library, for, advanced, Natural, Language, Processing, (, NLP, ), in, Python, .]


In [14]:
tableData = ([token, token.shape_, token.is_alpha, token.is_stop,
              token.pos_, spacy.explain(token.pos_),
              token.tag_, spacy.explain(token.tag_),
              token.dep_, spacy.explain(token.dep_)] for token in doc)

pd.DataFrame(tableData, columns=["text", "shape", "alphanumeric", "stop word",
                                 "pos", "Coarse-grained part-of-speech",
                                 "tag", "Fine-grained part-of-speech",
                                 "dep", "Syntactic dependency relation"])

text  shape  alphanumeric  stop word    pos  \
0        spaCy  xxxXx          True      False      X   
1           is     xx          True       True    AUX   
2            a      x          True       True    DET   
3         free   xxxx          True      False    ADJ   
4            ,      ,         False      False  PUNCT   
5         open   xxxx          True      False    ADJ   
6            -      -         False      False  PUNCT   
7       source   xxxx          True      False   NOUN   
8      library   xxxx          True      False   NOUN   
9          for    xxx          True       True    ADP   
10    advanced   xxxx          True      False    ADJ   
11     Natural  Xxxxx          True      False  PROPN   
12    Language  Xxxxx          True      False  PROPN   
13  Processing  Xxxxx          True      False  PROPN   
14           (      (         False      False  PUNCT   
15         NLP    XXX          True      False  PROPN   
16           )      )         False      False  PUNCT   
17          in     xx          True       True    ADP   
18      Python  Xxxxx          True      False  PROPN   
19           .      .         False      False  PUNCT   

   Coarse-grained part-of-speech    tag  \
0                          other    ADD   
1                      auxiliary    VBZ   
2                     determiner     DT   
3                      adjective     JJ   
4                    punctuation      ,   
5                      adjective     JJ   
6                    punctuation   HYPH   
7                           noun     NN   
8                           noun     NN   
9                     adposition     IN   
10                     adjective     JJ   
11                   proper noun    NNP   
12                   proper noun    NNP   
13                   proper noun    NNP   
14                   punctuation  -LRB-   
15                   proper noun    NNP   
16                   punctuation  -RRB-   
17                    adposition     IN   
18                   proper noun    NNP   
19                   punctuation      .   

                  Fine-grained part-of-speech       dep  \
0                                       email     nsubj   
1           verb, 3rd person singular present      ROOT   
2                                  determiner       det   
3                                   adjective      amod   
4                     punctuation mark, comma     punct   
5                                   adjective      amod   
6                    punctuation mark, hyphen     punct   
7                      noun, singular or mass  compound   
8                      noun, singular or mass      attr   
9   conjunction, subordinating or preposition      prep   
10                                  adjective      amod   
11                      noun, proper singular  compound   
12                      noun, proper singular  compound   
13                      noun, proper singular      pobj   
14                         left round bracket     punct   
15                      noun, proper singular     appos   
16                        right round bracket     punct   
17  conjunction, subordinating or preposition      prep   
18                      noun, proper singular      pobj   
19          punctuation mark, sentence closer     punct   

   Syntactic dependency relation  
0                nominal subject  
1                           None  
2                     determiner  
3            adjectival modifier  
4                    punctuation  
5            adjectival modifier  
6                    punctuation  
7                       compound  
8                      attribute  
9         prepositional modifier  
10           adjectival modifier  
11                      compound  
12                      compound  
13         object of preposition  
14                   punctuation  
15         appositional modifier  
16                   punctuation  
17        prepositional modifier  
18 

## List of noun phrases in the document

In [15]:
pd.DataFrame((chunk.text for chunk in doc.noun_chunks), columns=["text"])

text
0           a free, open-source library
1  advanced Natural Language Processing
2                                   NLP
3                                Python

## List of named entities, phrases and concepts

In [16]:
pd.DataFrame(([entity.text, entity.label_] for entity in doc.ents), columns=["text", "label"])

text label
0  Natural Language Processing   ORG
1                          NLP   ORG
2                       Python   GPE